name: $PluginName
version: $PluginVersion
main: $PluginMain
depend: [Kotlin, Tap]
author: BlackAnge1
api-version: '1.13'
commands:
  hello:
    usage: /<command>
    description: Hello?
  gm:
    usage: /<command>
    description: Reference of Essentials. Change gamemode.
